### ISSUE TITLE
Buy an UPORDOWN contract

### ISSUE THREAD

**Issue by programmerwith** [mdn522/binaryapi#11]
Hi, i'm trying to buy an up or down contract but i always have a barrier error, this type of contract has no barrier

from binaryapi.stable_api import Binary
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(message)s')

binary = Binary(token="XXXXXXXXX") ###accesso all'account

binary.buy(contract_type="UPORDOWN",  amount=10, symbol="AUDJPY", duration=5, duration_unit='m')

response:

{"echo_req":{"amount":10,"basis":"stake","contract_type":"UPORDOWN","currency":"USD","duration":5,"duration_unit":"m","product_type":"basic","proposal":1,"req_id":4,"symbol":"AUDJPY"},"error":{"code":"ContractCreationFailure","details":{"field":"barrier"},"message":"Invalid barrier (Double barrier input is expected)."},"msg_type":"proposal","req_id":4}

what's the problem? thank you

**Comment by mdn522** [comment]
Please try with `binary.api.buy` instead of `binary.buy` and let me know if it works

**Comment by programmerwith** [comment]
nothing, but the response changed:

binary.api.buy(contract_type="UPORDOWN", amount=10, symbol="AUDJPY", duration=5, duration_unit='m')     
TypeError: __call__() got an unexpected keyword argument 'contract_type'

**Comment by mdn522** [comment]
Please read the binary api documentation for parameters.
binary.api.buy takes mostly all parameters mentioned in binary.com api documentation

**Comment by luizhvac** [comment]
> Please read the binary api documentation for parameters.
> binary.api.buy takes mostly all parameters mentioned in binary.com api documentation

@mdn522 Could you exemplify how to use binary.api.buy? Even reading the documentation, I still couldn't use it for DIGITOVER with barrier 2.

**Comment by mdn522** [comment]
There are two ways to buy a contract. one is you propose for a contract pricing and then buy a contract using buy_id provided by the price proposal and the other way you can instantly buy a contract by passing data to parameter argument in binary.api.buy(parameter=data) method

Please have a look at this [file](https://github.com/mdn522/binaryapi/blob/master/examples/propose_and_buy_contract.py). 
it uses binary.api.proposal() and then binary.api.buy() API to buy a contract

In theory, you can use any contract type as long as you are passing the right parameters to the proposal() API according to the contract type.

Docs:
https://developers.binary.com/api/#proposal
https://developers.binary.com/api/#buy

**Comment by mdn522** [comment]
This issue is closed because it has been inactive
