### ISSUE TITLE
Potential profit or loss of current transaction

### ISSUE THREAD

**Issue by usherreuben** [mdn522/binaryapi#12]
how can i use the api to extract the profit or loss of current transaction
or check result

also how do i get the current candle or last two candle from the API

**Suggesttion**
i think if you upload a simple test bot, most of the api function and object question will be answered.
the doc  at  https://developers.binary.com/api/ is more confusing when one is not used to json

thank you

**Comment by mdn522** [comment]
I think you can subscribe to proposal and contracts for any changes (not tested but documentation says so(
I have added a subscribe parameter to buy function in stable API. you need to supply a callback function to read any message returned from websocket server though.

**Comment by mdn522** [comment]
This issue is closed because it has been inactive
