### ISSUE TITLE
How to check the result of an operation by 'contract_id'?

### ISSUE THREAD

**Issue by dylotrons** [mdn522/binaryapi#13]
How to check the result of an operation by 'contract_id'?

![image](https://user-images.githubusercontent.com/46464159/115278670-1a758e00-a11c-11eb-8b47-872d11a3c071.png)

**Comment by mdn522** [comment]
Trying seeing the message received by websocket server using a callback function

Example
```python
def message_handler(message):
    msg_type = message.get('msg_type')
    print("MSG", msg_type, "=>", message)

binary = Binary(token="your binary token", message_callback=message_handler)
```
I think when a contract expires. the server sends a message. (not 100% sure)

also you can subscribe to contract to receive updates from the server using `subscribe=True` in `binary.buy()` or `binary.api.buy()` method (you need callback function to get see those message)

**Comment by mdn522** [comment]
This issue is closed because it has been inactive
