### ISSUE TITLE
Cannot get data

### ISSUE THREAD

**Issue by Alzabel999999** [mdn522/binaryapi#16]
I try to get candle by ticks_history. But always get an int in response. Why that?

in example:
from binaryapi.stable_api import Binary
binary = Binary(token)
candles = binary.api.ticks_history(ticks_history="frxEURUSD", end="latest", style="candles")
print(candles)

**Comment by mdn522** [comment]
The `int` you get in return is `req_id` used in your request to Binary.com WebSocket server

to get the data you are looking for. you need to have a `message_handler` function shown below

```python
def message_handler(message):
    msg_type = message.get('msg_type')
    
    print(msg_type, "=>", message)

binary = Binary(token="YOUR-API-TOKEN-GOES-HERE", message_callback=message_handler)
```

**Comment by Alzabel999999** [comment]
ok, I get an info about my account after adding handler as argument to Binary. But when call method,nothing happen(

**Comment by Alzabel999999** [comment]
Ok, i get data. But when in method Subcsribe=True. How I can get by one request?

**Comment by mdn522** [comment]
There are two API endpoints for getting ticks data. Can you explore both of them to understand which one is suitable for your need

Ticks Stream: (If you want live ticks data then you probably need this according to the docs. you have to `subscribe` too)
https://api.deriv.com/playground/#ticks

Ticks History:
https://api.deriv.com/playground/#ticks_history

**Comment by mdn522** [comment]
This issue is closed because it has been inactive
