### ISSUE TITLE
I can't use a handle message function

### ISSUE THREAD

**Issue by GeraldoCruzeiro** [mdn522/binaryapi#19]
I've tried in every way to use the message handle function and it always gives an error.
Can you please give an example of a script with a request for some function and the correct way to get the response using the handle message function.

Thank you very much in advance

**Comment by mdn522** [comment]
Can I see the error and code if possible. without context, I can't really debug

Also look at this file: https://github.com/mdn522/binaryapi/blob/master/examples/print_tick_stream.py

And don't forget to update the library (binaryapi) to latest version
