### ISSUE TITLE
Problem with code in readme

### ISSUE THREAD

**Issue by lechna** [mdn522/binaryapi#2]
Hi,

thank you for youre work.
I have tried to run the code from the readme, "Getting Started". But i get an error:
     TypeError: __call__() missing 1 required positional argument: 'currency'
Can you please help me to solve the problem?

![image](https://user-images.githubusercontent.com/33435286/87710148-ac272800-c7a5-11ea-8196-048f279af3f0.png)

**Comment by mdn522** [comment]
Can you update the library and check again.
I pushed new code to fix this issue.

**Comment by lechna** [comment]
Now i get another error. I fixed it by adding following line into proposel.py line 62.
            "basis": "payout"
 https://github.com/mdn522/binaryapi/blob/003515b8c1ca004f5a2d6517b0ef83254cfc2f59/binaryapi/ws/chanels/proposal.py#L63



After that comes another error. The proposel is ok i think but something is wrong with the buy call. Had no time to check it yet:

![image](https://user-images.githubusercontent.com/33435286/88234259-f2cec380-cc78-11ea-89a9-7c1976a64a32.png)

**Comment by mdn522** [comment]
Sorry for the issue
I pushed another code. please update the package and try

Also, the code needs heavy testing

**Comment by lechna** [comment]
Thank you, now it works fine.

**Comment by mdn522** [comment]
I am closing this issue as it has been resolved.
