### ISSUE TITLE
problem with buy

### ISSUE THREAD

**Issue by Alzabel999999** [mdn522/binaryapi#20]
When I try an examle binary.buy('put',.....), I get:
'message': 'Trading is not offered for this duration.'
I had duration 3. I try 1,try 180.but get the same

**Comment by mdn522** [comment]
Can I see the full code. asset, duration, duration_unit etc.


Also have a look into these APIs
https://developers.binary.com/api/#proposal
https://developers.binary.com/api/#buy

**Comment by Alzabel999999** [comment]
Hi
binary.buy("put", amount=10, symbol=frxEURGBP, duration=3, duration_unit="t")

**Comment by mdn522** [comment]
The minimum pair for Forex Pairs is `5 ticks` I think. If you want duration unit to be minute then change `duration_unit`'s value to be `m` for minute

`duration_unit="m"`

**Comment by Alzabel999999** [comment]
Worked,thanks
