### ISSUE TITLE
Bug Error

### ISSUE THREAD

**Issue by 150Kirill150** [mdn522/binaryapi#23]
from binaryapi.stable_api import Binary

binary_token = "*************"

binary = Binary(token=binary_token)

symbol = "frxEURUSD"
print("Buy a CALL contract")
print(binary.buy('CALL', amount=1, symbol=symbol, duration=5, duration_unit='t'))

DEBUG:binaryapi.api:{"authorize": "************", "req_id": 1}
ERROR:websocket:error from callback <bound method WebsocketClient.on_message of <binaryapi.ws.client.WebsocketClient object at 0xb654ada8>>: on_message() takes 2 positional arguments but 3 were given
ERROR:binaryapi.ws.client:on_message() takes 2 positional arguments but 3 were given

**Comment by mdn522** [comment]
Please update the library again. it appears that some functions were not compatible with websocket-client library. which I tried to fix

```bash
pip3 install -U git+git://github.com/mdn522/binaryapi.git
```

**Comment by 150Kirill150** [comment]
Traceback (most recent call last):
  File "/home/kirill/Мои проекты/Selenium/binaryapi.py", line 2, in <module>
    from binaryapi.stable_api import Binary
  File "/home/kirill/Мои проекты/Selenium/binaryapi.py", line 2, in <module>
    from binaryapi.stable_api import Binary
ModuleNotFoundError: No module named 'binaryapi.stable_api'; 'binaryapi' is not a package
How to install this library?
This command was entered by `pip3 install -U git+git://github.com/mdn522/binaryapi.git`

**Comment by mdn522** [comment]
It seems like the name of your file is the same as the library (`binaryapi`) name. you have to rename the `binaryapi.py` to something else.

**Comment by mdn522** [comment]
> It seems like the name of your file is the same as the library (`binaryapi`) name. you have to rename the `binaryapi.py` to something else.

For reference: https://stackoverflow.com/a/54335336/4854605

**Comment by 150Kirill150** [comment]
Everything works, thank you!!!!!

**Comment by 150Kirill150** [comment]
I actually named one of the files binariyapi.py
