### ISSUE TITLE
Payout

### ISSUE THREAD

**Issue by dolglao** [mdn522/binaryapi#25]
Hello! Why am i receiving a different payout amount? 
![image](https://user-images.githubusercontent.com/92553537/137404883-c483fe4a-3333-4b1a-a1cc-a55d633f762e.png)
![image](https://user-images.githubusercontent.com/92553537/137404936-f6d0935d-cd24-43ed-96a8-5fdb0e10efc0.png)

**Comment by mdn522** [comment]
Payout keeps fluctuating/changing all the time. AFAIK the more volatile the market. the higher the payout will be. there might be some hidden factors too. which we might not be aware of.
