### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by chirathiwat** [mdn522/binaryapi#26]
Hello, I want to add Check win system.

**Comment by mdn522** [comment]
AFAIK binary does not have a direct check win system. but you should be able to check for win or loss using `transaction` message returned from the server. and comparing the `amount` data

You can read transaction messages using `message_handler`/`message_callback` function (README)
below I have provided an example for `message_handler` function.
```python
def message_handler(message):
    msg_type = message.get('msg_type')

    if msg_type == 'transaction':
        tx = message['transaction']  # tx = transaction

        if tx['action'] in ['buy', 'sell']:
            # print(msg_type, tx)  # Full data
            print(msg_type, {k: tx[k] for k in ['contract_id', 'action', 'amount', 'currency', 'longcode']})  # Short data
```

things to note
- transaction `action`:
  - buy = when you buy a contract
  - sell = when your contract is sold/expired/over
- transaction `contract_id`:
  - You get a contract_id every time you buy a contract
- when transaction `action`=`'sell'`
  - transaction `amount` => `0` should usually mean win. and if it's `0` or less then it's loss (it might differ)

DOCS: https://developers.binary.com/api/#transaction

**Comment by chirathiwat** [comment]
Can you make an api of alpari broker? How can I contact you?

link alpari    https://alpari.com/en/fix-contracts/#expanded

**Comment by mdn522** [comment]
> Can you make an api of alpari broker? How can I contact you?
> 
> link alpari https://alpari.com/en/fix-contracts/#expanded

I am not really into options brokers nowadays. but looking at Alpari's fixed contracts. they are using WebSocket to communicate. it should not be that hard to replicate in python or any other high-level programming language.
