### ISSUE TITLE
hi,

### ISSUE THREAD

**Issue by Jephpico** [mdn522/binaryapi#28]
does this api(project) work with deriv broker?
i saw the endpoint urls as  binary.com

**Comment by mdn522** [comment]
Yes. You are right. there API URL is the same. they just rebranded the company.

**Comment by andreker00** [comment]
I have been looking for a PocketOption broker API for a long time and I have found a DLL for that broker. I've tried decompiling, but I still don't understand much

**Comment by mdn522** [comment]
> I have been looking for a PocketOption broker API for a long time and I have found a DLL for that broker. I've tried decompiling, but I still don't understand much

Please don't hijack the issue. and about the question. I am not really into options brokers nowadays. AFAIK pocket option uses WebSocket. if you can figure out how they communicate browser to the server using WebSocket then it should not be that hard to replicate.
