### ISSUE TITLE
Problem getting the maximum payment.

### ISSUE THREAD

**Issue by GeraldoCruzeiro** [mdn522/binaryapi#29]
Hello how are you? first, great job you did with this API, congratulations...
The problem I'm having is that the payout for volatile indexes is set at 95.5% in the broker's app, but in the API I'm only getting paid 78%, isn't there something in the API that is limiting the payout %?

**Comment by mdn522** [comment]
Payout keeps fluctuating/changing all the time. AFAIK the more volatile the market. the higher the payout will be. there might be some hidden factors too. which we might not be aware of. after all, it's Binary Options Broker.
