### ISSUE TITLE
 I'm just getting numbers

### ISSUE THREAD

**Issue by pabloapdz** [mdn522/binaryapi#3]
I didn't quite understand why, but the only thing I get as an answer is numbers in an increasing way. I will put two code samples:

First:
```
# High Level API, This API is based on "binaryapi.api" for easy usage
from binaryapi.stable_api import Binary
# Low Level API
from binaryapi.api import BinaryAPI

binary = Binary(token="my_token")

stats = binary.api.get_account_status(1)
print('account status ',stats)
```

**Respsonse: 4**

Second:
```
# High Level API, This API is based on "binaryapi.api" for easy usage
from binaryapi.stable_api import Binary
# Low Level API
from binaryapi.api import BinaryAPI

binary = Binary(token="my_token")
import time

# Ticks API - https://developers.binary.com/api/#ticks
while True:
	a = binary.api.ticks(ticks="frxEURUSD", subscribe=None, passthrough=None, req_id=None)
	print(a)
	time.sleep(1)
```

Respsonse:
**4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20**

**Comment by mdn522** [comment]
The number you get is request id(req_id) for that particular WebSocket request.

For now the only way you can get those data is by using a message callback function

example

```python
def message_handler(message):
    # message = json.loads(str(message))
    msg_type = message.get('msg_type')
    print("MSG", msg_type, "=>", message)

binary = Binary(token="my_token", message_callback=message_handler)
```

Now if you call get_account_status(), ticks() etc. You should see data coming in to that message handler(callback) function

**Comment by mdn522** [comment]
Also no need to call the ticks() function multiple times for the same pair. that function just subscribes to tick data and then tick data will come to the message handler/callback function.

**Comment by pabloapdz** [comment]
Thanks ! You're right.
