### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [mdn522/binaryapi#30]
Hi
I am trying to install your library but shell give me some errors:
`C:\Users\Jhon>pip install -U git+git://github.com/mdn522/binaryapi.git
Collecting git+git://github.com/mdn522/binaryapi.git
  Cloning git://github.com/mdn522/binaryapi.git to c:\users\jhon\appdata\local\temp\pip-req-build-wcdwqrhl
  Running command git clone --filter=blob:none --quiet git://github.com/mdn522/binaryapi.git 'C:\Users\Jhon\AppData\Local\Temp\pip-req-build-wcdwqrhl'
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/mdn522/binaryapi.git 'C:\Users\Jhon\AppData\Local\Temp\pip-req-build-wcdwqrhl' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/mdn522/binaryapi.git 'C:\Users\Jhon\AppData\Local\Temp\pip-req-build-wcdwqrhl' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by JhonAndersonVelasco** [comment]
Sorry, I readed the docs in [https://github.blog/2021-09-01-improving-git-protocol-security-github/](url) so, I wrote it:

`pip install -U git+https://github.com/mdn522/binaryapi.git`

And it installed fine

Thank you for your work

**Comment by mdn522** [comment]
Thanks. I will update the Readme
