### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bidreshivaprasad** [mdn522/binaryapi#31]
"C:\Python310\lib\site-packages\websocket_client-0.56.0-py3.10.egg\websocket\_app.py", line 343, in _callback
    callback(*args)

**Comment by mdn522** [comment]
Can you give the whole stacktrace? it will be more helpful to debug

**Comment by mdn522** [comment]
also, can you try installing websocket-client using `pip install websocket-client==1.2.1`

**Comment by bidreshivaprasad** [comment]
thanks sir
