### ISSUE TITLE
get contract result win or loss

### ISSUE THREAD

**Issue by bidreshivaprasad** [mdn522/binaryapi#32]
I now basic of python pls help me sir
This is my buy contract 
```
from binaryapi.stable_api import Binary

binary_token = 'xxxxxxxxxxxxx'

binary = Binary(token=binary_token)

symbol = "R_75"  # symbol/asset

success,contract_id, req_id = binary.buy('PUT',subscribe = 1, amount=1, symbol=symbol, duration=5, duration_unit='t')

print('success={}, contract_id={}, req_id={}'.format(success, contract_id, req_id))
```
and I need the result of buy trade `(contract_id)`

**Comment by mdn522** [comment]
As I can see you have already `subscribed` to the `buy contract`. Now you need a message handler to proccess messages received from the server

Simple example for message handler: https://github.com/mdn522/binaryapi#authorizelogin-with-a-message-handler-function

**Comment by bidreshivaprasad** [comment]
Ok sir

**Comment by bidreshivaprasad** [comment]
How to make copy trading

**Comment by mdn522** [comment]
Binary already has copy trading feature including API access

https://api.deriv.com/api-explorer/#copy_start

you should be able to call it with `binary.api.copy_start(...your params...)`

but if you are interested in your own copy trading service. I recommend learning about data-polling/websocket for live/low latency data transfer from master to copier (signal) and act according to it

**Comment by bidreshivaprasad** [comment]
sir pls provide code

**Comment by mdn522** [comment]
I don't have a code for it

**Comment by bidreshivaprasad** [comment]
ok
