### ISSUE TITLE
demo balance 

### ISSUE THREAD

**Issue by boopathiviky** [mdn522/binaryapi#33]
Is the API work with demo balance.i want trade with my demo balance.
For that would happened?
what i have to do?

**Comment by mdn522** [comment]
You need a API key from demo account. Which you can create/find in account settings. Make sure demo account is selected

**Comment by boopathiviky** [comment]
Can you tell me about proposal vs buy?

**Comment by mdn522** [comment]
Have a look at this example: https://github.com/mdn522/binaryapi/blob/master/examples/propose_and_buy_contract.py

Before you buy a contract. you normally ask for proposals. when the server gives you proposal data. if you like the payout/market price/etc value in proposal data. you buy it. this is a simple explanation
