### ISSUE TITLE
API: Top Up Virtual-Money Account

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [mdn522/binaryapi#34]
Thank you by your work first at all...

I wanna reset my demo balance with:

`Binary(token=token).api.topup_virtual:1`

But doesn't works, what can I do?

**Comment by mdn522** [comment]
The system is invalid for Python.
Try calling `Binary(token=token).api.topup_virtual()`
If it does not work. let me know

TIP: It's better to store `Binary(token=token)` as a variable and access the variable.

**Comment by mdn522** [comment]
DOCS: https://api.deriv.com/api-explorer/#topup_virtual

**Comment by JhonAndersonVelasco** [comment]
Thank you

This worked!

`binary.api.topup_virtual(1)`

**Comment by mdn522** [comment]
> Thank you
> 
> This worked!
> 
> `binary.api.topup_virtual(1)`

You can opt out the `1`. The library automatically includes that `1`
