### ISSUE TITLE
Now other issue

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [mdn522/binaryapi#35]
`DEBUG:binaryapi.ws.client:Websocket client connected.
DEBUG:binaryapi.api:{"authorize": "xxxxxxxxxxxxxxxxxxxxx", "req_id": 48}
DEBUG:binaryapi.ws.client:{"authorize":{"account_list":[{"account_type":"trading","created_at":1616442487,"currency":"USD","is_disabled":0,"is_virtual":0,"landing_company_name":"svg","loginid":"CR2256814","trading":{}},{"account_type":"trading","created_at":1616265606,"currency":"USD","is_disabled":0,"is_virtual":1,"landing_company_name":"virtual","loginid":"VRTC3993956","trading":{}}],"balance":10003.95,"country":"co","currency":"USD","email":"XXXXXXXX@gmail.com","fullname":"  ","is_virtual":1,"landing_company_fullname":"Deriv Limited","landing_company_name":"virtual","local_currencies":{"COP":{"fractional_digits":2}},"loginid":"VRTC3993956","preferred_language":"ES","scopes":["read","trade","admin","trading_information"],"trading":{},"upgradeable_landing_companies":["svg"],"user_id":8106808},"echo_req":{"authorize":"<not shown>","req_id":48},"msg_type":"authorize","req_id":48}
DEBUG:binaryapi.ws.client`

This is a real issue...

**Comment by JhonAndersonVelasco** [comment]
My code is:

`def Operacion(binary,tipo:str, monto:float, simbolo:str, duracion:int): # Enviar operación a binary

   success, contract_id, req_id = binary.buy(tipo, 
                                             amount=monto, 
                                             symbol=simbolo, 
                                             duration=duracion, 
                                             duration_unit='s')

   return success, contract_id, req_id`

`if Pred1 > Pred0:

                    print('[OPE]\tEnviando operación CALL')

                    oper = Operacion(binary, 'CALL', MontoAct, ConvSimb(simb), 55)

                    if oper[0] == True:
                        
                        UltOper = 'Sí'
                        print('[OPE]\tOperación CALL enviada con éxito!')
                        print('[OPE]\tContrato = {},  Req_id = {}'.format(oper[1],  oper[2]))
                        print('[OPE]\tSímbolo = {},  Monto = {} {}\n'.format(simb,  MontoAct,  Moneda))
                        
                    else:
                        
                        UltOper = 'No'
                        print('[ERR]\tLa operación no ha sido enviada!\n')
                        binary.api.connect()
                        #time.sleep(120)

                elif Pred1 < Pred0:

                    print('[OPE]\tEnviando operación PUT')

                    oper = Operacion(binary, 'PUT', MontoAct, ConvSimb(simb), 55)

                    if oper[0] == True:
                        
                        UltOper = 'Sí'
                        print('[OPE]\tOperación PUT enviada con éxito!')
                        print('[OPE]\tContrato = {},  Req_id = {}'.format(oper[1],  oper[2]))
                        print('[OPE]\tSímbolo = {},  Monto = {} {}\n'.format(simb,  MontoAct,  Moneda))
                        
                    else:
                        
                        UltOper = 'No'
                        print('[ERR]\tLa operación no ha sido enviada!\n')
                        binary.api.connect()
                        #time.sleep(120)`

**Comment by mdn522** [comment]
Does it buy the contract?
In your first comment. It's all debug log. I see no errors their. If you are not interested in printed debug log. Then disable it. (Remove import `logging` and anything related to it)

**Comment by mdn522** [comment]
Also in your first comment, you API key is included their along with your account id. You might have forgotten to remove them before posting. For API Key you can delete it and recreate another

**Comment by JhonAndersonVelasco** [comment]
Hi, thank you
That's the problem, I am not using logging and it appears after some successful operations

**Comment by mdn522** [comment]
For `logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(message)s')`

try changing `logging.DEBUG` to `logging.ERROR`


I can't test it myself right now

**Comment by JhonAndersonVelasco** [comment]
Thank you

I already have for tensorflow:

`os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'`

But also I tryed your suggestion but doesn't work
