### ISSUE TITLE
contract payout

### ISSUE THREAD

**Issue by zhui064** [mdn522/binaryapi#36]
I run the python script  "examples/propose_and_buy_contract.py" .  The payout  is  always significantly lower than that I saw in browser page at the same time ?  Any other settings such as currency, duration remain the same.

E.g.  It displayed "85% Return" in browser page, but only about 70% from runing the python script.

**Comment by mdn522** [comment]
Payout keeps fluctuating/changing all the time. AFAIK the more volatile the market. the higher the payout will be. there might be some hidden factors too. which we might not be aware of. after all It's Binary Options you know

**Comment by zhui064** [comment]
I tried many times and always large different. I am sure that It 's  not because of the payout fluctuating. you can try to run  the scripts. Maybe the system of Binary.com set up disparity.

**Comment by JhonAndersonVelasco** [comment]
I supposed it's because we are using the API and the rates are different

**Comment by mdn522** [comment]
I am not sure. It also can be like this that to visually attract, the payout is different on web UI. it's a wild guess
