### ISSUE TITLE
Get all positions

### ISSUE THREAD

**Issue by bidreshivaprasad** [mdn522/binaryapi#38]
How to get all opend positions id

**Comment by mdn522** [comment]
Let me know if this one solves your issue. 

**Price Proposal: Open Contracts** API
https://binaryapi.readthedocs.io/en/latest/api/proposal_open_contract.html

To get messages from server
https://binaryapi.readthedocs.io/en/latest/getting_started.html#authorize-login-with-a-message-handler-callback-function
