### ISSUE TITLE
Connection is already closed.

### ISSUE THREAD

**Issue by codingsett** [mdn522/binaryapi#5]
I keep get Connection is already closed. error after sometime how do i reconnect to the websocket without rerunning the script?

Here is a snippet of what i have tried so far but doesnt work

``` 
def deriv():
     binary = Binary(token=binary_token, message_callback=message_handler)
     . . . . . . . . . 
     while 1:
           try:
               trade()
           except:
              #connection closed
               deriv()
```

Any help would be appreciated thanks!

**Comment by mdn522** [comment]
Sorry for late reply. Do you still have this issue? If yes then please check your latency with binary.com websocket server. Check if it's stable or not

**Comment by mdn522** [comment]
Check the `/examples` folder for script called `auto_reconnect.py` to gain some ideas
