### ISSUE TITLE
error message when trying to install bynariapi

### ISSUE THREAD

**Issue by gchumbes** [mdn522/binaryapi#6]
hi i got following error message when trying to install bynariapi with spyder and python 3.8.3

In [188]:pip install -U git+git://github.com/mdn522/binaryapi.git

Collecting git+git://github.com/mdn522/binaryapi.git
  Cloning git://github.com/mdn522/binaryapi.git to c:\users\gusta\appdata\local\temp\pip-req-build-fwhze4r9
Note: you may need to restart the kernel to use updated packages.
  Running command git clone -q git://github.com/mdn522/binaryapi.git 'C:\Users\gusta\AppData\Local\Temp\pip-req-build-fwhze4r9'
  ERROR: Error [WinError 2] El sistema no puede encontrar el archivo especificado while executing command git clone -q git://github.com/mdn522/binaryapi.git 'C:\Users\gusta\AppData\Local\Temp\pip-req-build-fwhze4r9'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by mdn522** [comment]
You need to install git and have git in your system path

Git Download: https://git-scm.com/downloads

**Comment by gchumbes** [comment]
thanks it worked, how could i get acces to the parameters of the response of the binary.buy or binary.api.proposal, i mean how could i get information about the payout value of the response which i see is printed automatically but i would like to get it as variable. sorry im not expert it may be a basic python question.

**Comment by mdn522** [comment]
https://github.com/mdn522/binaryapi/issues/3#issuecomment-699483228

Please have a look there. I hope it will solve your issue.

**Comment by gchumbes** [comment]
hi that helps me alot, now i understand i should work in the message handler function, in case we want to work with forex i understand the format would be for example: 'frxGBPJPY' however do you have any idea why when i send a proposal with stake message the answer indicates a payout lower than the one i see directly on smarttrader in binary.com?

**Comment by mdn522** [comment]
The payout keeps fluctuating all the time I guess in the options market depending on volatility and other factors
