### ISSUE TITLE
Buy Touch contract error

### ISSUE THREAD

**Issue by ericleonardo** [mdn522/binaryapi#7]
Hello!
I'm getting error when trying to buy a Touch contract.
Just change the contract type to "ONETOUCH", and insert parameter "barrier=+1.00".
Then: ModuleNotFoundError: No module named 'binaryapi'.
If change back to "PUTE" contract type and delete barrier parameter, all works good for Put contract.

from binaryapi.stable_api import Binary
binary_token = "xxxxxxxxxxxxxxxxxx"
binary = Binary(token=binary_token)

**This works for Put contract:**
symbol = "R_100"
print("Buy a PUT contract")
print(binary.buy('PUTE', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

**This also works for Put contract:**
symbol = "R_100"
print("Buy a PUT contract")
print(binary.buy(**contract_type='PUTE',** amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

**This does not work (binaryapi module not found) for Touch contract:**
symbol = "R_100"
print("Buy a TOUCH contract")
print(binary.buy('ONETOUCH', barrier=+1.00, amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

**This also does not work (binaryapi module not found) for Touch contract:**
symbol = "R_100"
print("Buy a TOUCH contract")
print(binary.buy(**contract_type='ONETOUCH',** barrier='+1.00', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

Reference for Buy contract parameters:
https://developers.binary.com/api/#buy

Thank you so much for this Python Binary API!!

**Comment by ericleonardo** [comment]
Now I tried also running script on Spyder (IPhyton) and error message is more detailed:

Traceback (most recent call last):

  File "C:\Users\PC\Desktop\Test_Binary_Touch.py", line 17, in <module>
    print(binary.buy(contract_type='ONETOUCH', barrier='+1.0', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

TypeError: buy_call_put() got an unexpected keyword argument 'barrier'

**Comment by mdn522** [comment]
Please try to use binary.api.buy instead of binary.buy.

I am on my phone so can't really check myself.

**Comment by ericleonardo** [comment]
> 
> 
> Please try to use binary.api.buy instead of binary.buy.
> 
> I am on my phone so can't really check myself.

Hi.. This did not work.. didn't recognize arguments (amount, etc).

I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
Please, what number 5 in the error response represents?

**Comment by ericleonardo** [comment]
Now it works! I just tested again after a day.
Maybe I should close and restart Spyder/Python after editing library file.
Just added barrier parameter to library file and after a restart it is working.
Also tested for Call/Put and barrier parameter will just be ignored, even if used.

**Test for TOUCH:**

from binaryapi.stable_api import Binary
binary_token = "xxxxxxxxxxxxxxxxxx"
binary = Binary(token=binary_token)

symbol = "R_100"
barrier = "+1.00"
print("Buy a TOUCH contract")
print(binary.buy(contract_type='ONETOUCH', amount=1.01, symbol=symbol, duration=5, duration_unit='t', barrier=barrier))
=
**Buy a TOUCH contract
(True, 108503560908, 5)**


**Test for PUT:**

from binaryapi.stable_api import Binary
binary_token = "xxxxxxxxxxxxxxxxxx"
binary = Binary(token=binary_token)

symbol = "R_100"
barrier = "+1.00"
print("Buy a PUT contract")
print(binary.buy(contract_type='PUT', amount=1.01, symbol=symbol, duration=5, duration_unit='t', barrier=barrier))
=
**Buy a PUT contract
(True, 108505047188, 5)**

So, barrier parameter will be ignored for contracts that don't need it.
Some contract type may need two barriers, then will need including "Barrier2" parameter to library file like this.

What I did was including the **barrier** parameter to **stable_api.py**:

Line 62:
def buy_call_put(self, contract_type, amount, symbol, duration, duration_unit, **barrier,** min_payout=0,
                     basis=CONSTANTS.PROPOSAL_BASIS.STAKE, passthrough=None, req_id=None, no_proposal=False,
                     confirm_request=True):
Line 70:
if no_proposal:
            parameters = dict(symbol=symbol, duration=duration, duration_unit=duration_unit,
                              basis=CONSTANTS.PROPOSAL_BASIS.STAKE, amount=amount, **barrier=barrier,** currency=self.api.profile.currency, )

Line 74:
else:
            prop_req_id = self.api.proposal(contract_type=contract_type, currency=self.api.profile.currency,
                                            symbol=symbol, duration_unit=duration_unit,
                                            duration=duration, amount=amount, basis=basis, **barrier=barrier** )


This Python Binary API will be very useful to me!
THANK YOU!

**Comment by ericleonardo** [comment]
Very strange... Now it is not working again, and returning **(False, None, 5)**.
Is Binary blocking/rejecting contract purchase? Should I register app like said in the API guide?

https://developers.binary.com/guide/

Before using the API, you must register your application:

    1. Open an account at Binary.com (either a Virtual Account or a Real Account).
    2. Go to Security & Limits, select API token and create a new token with the admin scope.
    3. Register your app to obtain your app_id.

**Comment by ericleonardo** [comment]
Ok... Solved.
I registered a new app ID for my token, updated id on library and it's working again.

**Comment by mdn522** [comment]
Nice to see it's solved

Also try to have a look at this reply
https://github.com/mdn522/binaryapi/issues/3#issuecomment-699483228

here I have shown how to use the message handler/callback function to see/process returned messages from Binary WebSocket channel

**Comment by luizhvac** [comment]
> > Please try to use binary.api.buy instead of binary.buy.
> > I am on my phone so can't really check myself.
> 
> Hi.. This did not work.. didn't recognize arguments (amount, etc).
> 
> I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
> But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
> Please, what number 5 in the error response represents?

Hy friend.
How did you add the "barrier" parameter to stable_api.py?

I opened stable_api.py but I don't know where to add the "barrier".

Can you help me? Because I need to add "DIGITOVER", barrier = 2. How can I do it?

Thanks

**Comment by ericleonardo** [comment]
Now I tried also running script on Spyder (IPhyton) and error message is more detailed:

Traceback (most recent call last):

  File "C:\Users\PC\Desktop\Test_Binary_Touch.py", line 17, in <module>
    print(binary.buy(contract_type='ONETOUCH', barrier='+1.0', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

TypeError: buy_call_put() got an unexpected keyword argument 'barrier'

> 
> 
> > > Please try to use binary.api.buy instead of binary.buy.
> > > I am on my phone so can't really check myself.
> > 
> > 
> > Hi.. This did not work.. didn't recognize arguments (amount, etc).
> > I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
> > But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
> > Please, what number 5 in the error response represents?
> 
> Hy friend.
> How did you add the "barrier" parameter to stable_api.py?
> 
> I opened stable_api.py but I don't know where to add the "barrier".
> 
> Can you help me? Because I need to add "DIGITOVER", barrier = 2. How can I do it?
> 
> Thanks

Hi Luiz! (vc é do Brasil?)
Did you get to solve your issue? For me all is working perfectly here.
I even automate buy contract calling external Python script from MT5.

What I did to include Barrier parameter to stable_api.py (see the **bold** code):

Line 62:
def buy_call_put(self, contract_type, amount, symbol, duration, duration_unit, **barrier**, min_payout=0,
basis=CONSTANTS.PROPOSAL_BASIS.STAKE, passthrough=None, req_id=None, no_proposal=False,
confirm_request=True):

Line 70:
if no_proposal:
parameters = dict(symbol=symbol, duration=duration, duration_unit=duration_unit,
basis=CONSTANTS.PROPOSAL_BASIS.STAKE, amount=amount, **barrier=barrier**, currency=self.api.profile.currency, )

Line 74:
else:
prop_req_id = self.api.proposal(contract_type=contract_type, currency=self.api.profile.currency,
symbol=symbol, duration_unit=duration_unit,
duration=duration, amount=amount, basis=basis, **barrier=barrier** )

**Comment by luizhvac** [comment]
> Now I tried also running script on Spyder (IPhyton) and error message is more detailed:
> 
> Traceback (most recent call last):
> 
> File "C:\Users\PC\Desktop\Test_Binary_Touch.py", line 17, in
> print(binary.buy(contract_type='ONETOUCH', barrier='+1.0', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))
> 
> TypeError: buy_call_put() got an unexpected keyword argument 'barrier'
> 
> > > > Please try to use binary.api.buy instead of binary.buy.
> > > > I am on my phone so can't really check myself.
> > > 
> > > 
> > > Hi.. This did not work.. didn't recognize arguments (amount, etc).
> > > I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
> > > But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
> > > Please, what number 5 in the error response represents?
> > 
> > 
> > Hy friend.
> > How did you add the "barrier" parameter to stable_api.py?
> > I opened stable_api.py but I don't know where to add the "barrier".
> > Can you help me? Because I need to add "DIGITOVER", barrier = 2. How can I do it?
> > Thanks
> 
> Hi Luiz! (vc é do Brasil?)
> Did you get to solve your issue? For me all is working perfectly here.
> I even automate buy contract calling external Python script from MT5.
> 
> What I did to include Barrier parameter to stable_api.py (see the **bold** code):
> 
> Line 62:
> def buy_call_put(self, contract_type, amount, symbol, duration, duration_unit, **barrier**, min_payout=0,
> basis=CONSTANTS.PROPOSAL_BASIS.STAKE, passthrough=None, req_id=None, no_proposal=False,
> confirm_request=True):
> 
> Line 70:
> if no_proposal:
> parameters = dict(symbol=symbol, duration=duration, duration_unit=duration_unit,
> basis=CONSTANTS.PROPOSAL_BASIS.STAKE, amount=amount, **barrier=barrier**, currency=self.api.profile.currency, )
> 
> Line 74:
> else:
> prop_req_id = self.api.proposal(contract_type=contract_type, currency=self.api.profile.currency,
> symbol=symbol, duration_unit=duration_unit,
> duration=duration, amount=amount, basis=basis, **barrier=barrier** )

Hi Eric. (sou do Brasil)
Consegui conforme você ensinou aí, deu super certo. Obrigado meu amigo. 
Essa ferramenta é muito útil. Vai me ajudar bastante. Poderíamos conversar a respeito de projetos pra Binary.

I managed as you taught there, it worked very well. Thank you my friend.
This tool is very useful. It will help me a lot.

**Comment by ericleonardo** [comment]
Now I tried also running script on Spyder (IPhyton) and error message is more detailed:

Traceback (most recent call last):

  File "C:\Users\PC\Desktop\Test_Binary_Touch.py", line 17, in <module>
    print(binary.buy(contract_type='ONETOUCH', barrier='+1.0', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))

TypeError: buy_call_put() got an unexpected keyword argument 'barrier'

> 
> 
> > > Please try to use binary.api.buy instead of binary.buy.
> > > I am on my phone so can't really check myself.
> > 
> > 
> > Hi.. This did not work.. didn't recognize arguments (amount, etc).
> > I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
> > But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
> > Please, what number 5 in the error response represents?
> 
> Hy friend.
> How did you add the "barrier" parameter to stable_api.py?
> 
> I opened stable_api.py but I don't know where to add the "barrier".
> 
> Can you help me? Because I need to add "DIGITOVER", barrier = 2. How can I do it?
> 
> Thanks

Hi Luiz! (vc é do Brasil?)
Did you get to solve your issue? For me all is working perfectly here.
I even automate buy contract calling external Python script from MT5.

What I did to include Barrier parameter to stable_api.py (see the **bold** code):

Line 62:
def buy_call_put(self, contract_type, amount, symbol, duration, duration_unit, **barrier**, min_payout=0,
basis=CONSTANTS.PROPOSAL_BASIS.STAKE, passthrough=None, req_id=None, no_proposal=False,
confirm_request=True):

Line 70:
if no_proposal:
parameters = dict(symbol=symbol, duration=duration, duration_unit=duration_unit,
basis=CONSTANTS.PROPOSAL_BASIS.STAKE, amount=amount, **barrier=barrier**, currency=self.api.profile.currency, )

Line 74:
else:
prop_req_id = self.api.proposal(contract_type=contract_type, currency=self.api.profile.currency,
symbol=symbol, duration_unit=duration_unit,
duration=duration, amount=amount, basis=basis, **barrier=barrier** )

> 
> 
> > Now I tried also running script on Spyder (IPhyton) and error message is more detailed:
> > Traceback (most recent call last):
> > File "C:\Users\PC\Desktop\Test_Binary_Touch.py", line 17, in
> > print(binary.buy(contract_type='ONETOUCH', barrier='+1.0', amount=1.02, symbol=symbol, duration=5, duration_unit='t'))
> > TypeError: buy_call_put() got an unexpected keyword argument 'barrier'
> > > > > Please try to use binary.api.buy instead of binary.buy.
> > > > > I am on my phone so can't really check myself.
> > > > 
> > > > 
> > > > Hi.. This did not work.. didn't recognize arguments (amount, etc).
> > > > I also tried just adding the parameter "barrier" into stable_api.py library file, as this parameter was missing.
> > > > But I'm getting response from Binary server: Buy a TOUCH contract **(False, None, 5)**
> > > > Please, what number 5 in the error response represents?
> > > 
> > > 
> > > Hy friend.
> > > How did you add the "barrier" parameter to stable_api.py?
> > > I opened stable_api.py but I don't know where to add the "barrier".
> > > Can you help me? Because I need to add "DIGITOVER", barrier = 2. How can I do it?
> > > Thanks
> > 
> > 
> > Hi Luiz! (vc é do Brasil?)
> > Did you get to solve your issue? For me all is working perfectly here.
> > I even automate buy contract calling external Python script from MT5.
> > What I did to include Barrier parameter to stable_api.py (see the **bold** code):
> > Line 62:
> > def buy_call_put(self, contract_type, amount, symbol, duration, duration_unit, **barrier**, min_payout=0,
> > basis=CONSTANTS.PROPOSAL_BASIS.STAKE, passthrough=None, req_id=None, no_proposal=False,
> > confirm_request=True):
> > Line 70:
> > if no_proposal:
> > parameters = dict(symbol=symbol, duration=duration, duration_unit=duration_unit,
> > basis=CONSTANTS.PROPOSAL_BASIS.STAKE, amount=amount, **barrier=barrier**, currency=self.api.profile.currency, )
> > Line 74:
> > else:
> > prop_req_id = self.api.proposal(contract_type=contract_type, currency=self.api.profile.currency,
> > symbol=symbol, duration_unit=duration_unit,
> > duration=duration, amount=amount, basis=basis, **barrier=barrier** )
> 
> Hi Eric. (sou do Brasil)
> Consegui conforme você ensinou aí, deu super certo. Obrigado meu amigo.
> Essa ferramenta é muito útil. Vai me ajudar bastante. Poderíamos conversar a respeito de projetos pra Binary.
> 
> I managed as you taught there, it worked very well. Thank you my friend.
> This tool is very useful. It will help me a lot.

Bacana... claro, anota meu Telegram: @ericleonardocunha
Não sou especialista e nem tenho formação em programação mas quando preciso vou atrás até conseguir fazer.
Realmente essa ferramenta aqui é o q estava faltando.. muito boa.. Eu consegui até integrar ao MT5.

**Comment by mdn522** [comment]
I have added a new file in `/examples` folder called `propose_and_buy_contract.py`. it shows how you can propose for a contract pricing and then buy the contract.

**Comment by mdn522** [comment]
This issue is closed because it has been inactive
