### ISSUE TITLE
Buy a "DIGITOVER" contract

### ISSUE THREAD

**Issue by luizhvac** [mdn522/binaryapi#8]
Hy my friend!
I am trying to buy a "DIGITOVER" contract but the parameters do not accept.
The return is False, None, 4.
I believe it is for lack of "barrier". how can I buy "DIGITOVER", barrier = 2?

This does not work  for DIGITOVER contract:
```
symbol = "R_100"
print("Buy a Digit Over contract")
print(binary.buy('DIGITOVER', barrier=2, amount=1, symbol=symbol, duration=1, duration_unit='t'))
```

I read in another "issue" that has to add "barrier" in stable_api.py but I don't know how to do that.

How can I do it?

**Comment by mdn522** [comment]
Can you try binary.api.buy instead of binary.buy

**Comment by luizhvac** [comment]
> Can you try binary.api.buy instead of binary.buy


I managed to add barrier = barrier as taught by Ericleonardo.
Thank you very much for making this extremely useful tool available. Thank you very much mdn522
