### ISSUE TITLE
how do I get the PROFIT Balance?

### ISSUE THREAD

**Issue by luizhvac** [mdn522/binaryapi#9]
I can't use the api to extract the Balance from the message below. How do I do?

```
def message_handler(message):
    # message = json.loads(str(message))
    msg_type = message.get('msg_type')
    print("MSG", msg_type, "=>", message)

binary = Binary(token="my_token", message_callback=message_handler)
```

**Comment by mdn522** [comment]
Please try

`binary.api.profile.balance`

to get the balance

or if you want to see the profit from trades. it should appear in the message_callback function.

**Comment by luizhvac** [comment]
Hi @mdn522 , thanks for the answer. But did not give right:

![image](https://user-images.githubusercontent.com/71279125/110027257-8177e880-7d10-11eb-9daa-b4a407a77958.png)

**Comment by mdn522** [comment]
`binary.api.profile.balance` is a property/attribute not a function

example 
```python
print(binary.api.profile.balance)
```

Or if you want to call the balance WebSocket function then use

```python
binary.api.balance()
# Parameters -> binary.api.balance(account=None, subscribe=None)
```

**Comment by luizhvac** [comment]
Thanks @mdn522 , This worked!
